// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wopkvcxrievauodvtupe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvcGt2Y3hyaWV2YXVvZHZ0dXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDYyMzcsImV4cCI6MjA2NDMyMjIzN30.SUDU-X8X72IefgKA1O03JqFOPWa2OphOUFPv23s-pi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);